---
bases:
  - ../base
resources:
  - ingress.yaml
patchesStrategicMerge:
  - ./www.yaml
secretGenerator:
  - name: service-cert
    type: "kubernetes.io/tls"
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
